language: node_js

node_js:
  - "0.10"

branches:
  except:
    - gh-pages

env:
  global:
    - REPO="git@github.com:hackfoldr/hackfoldr"
    - secure: "RI6I/GmBk25+vLkzzxE96TApubipiAnwUu8DoCBbaMlkeMDc+JRS4LDC+Utx\nEDIisAUYyXOXIWsOg2CgTH5zSZL+fOTqHa98uY/OWqUTz+jT49QS7mccvZid\nA0liRzo6pKw5KrvAtFi5yZ0ixE9JS6zE4Gk7+7nrP3js+BL/ZJU="
    - GOOGLE_API_BROWSER_APPLICATION_KEY="AIzaSyCHm8NgD_p5F_-e7euH8BZiB4wSB8pOZ2A"

after_success: .travis/after_success.sh
