language: node_js

node_js:
  - "0.10"

before_install:
  - gem install sass compass
  - sass --version

branches:
  except:
    - gh-pages

env:
  global:
    - REPO="git@github.com:g0v/hack.g0v.tw"
    - secure: "ijNdxgn/u65qneErGypdELU9bGkiJbzCT2M2oJEKml3H6uf9M3rCbfU8dxwD\nx2qwqO9kpxCjFxz7324OZPDlmZfdVrZwW30Ecyrnxhr1EhuSB5KsF2Q92+J3\nF+fkMnsC/NTHEDCxI1ge4A7tBaPA3oQRjvrj3shilxIOn+z+SkM="

after_success: .travis/after_success.sh
